# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Opo_GfDrBFb1i3xt7QeiHNsERa2gAwt
"""

import csv
import networkx as nx
import matplotlib.pyplot as plt
from math import radians, sin, cos, sqrt, atan2

# ======================
# 1️⃣ Haversine Distance
# ======================
def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0  # Earth radius in km
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    dlat, dlon = lat2 - lat1, lon2 - lon1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    return R * 2 * atan2(sqrt(a), sqrt(1 - a))

# ==============================
# 2️⃣ Load station data from CSV
# ==============================
def load_stations(filename):
    stations = []
    with open(filename, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                lat = float(row['Latitude'])
                lon = float(row['Longitude'])
                name = row['Station Names'].strip()
                stations.append({'Station': name, 'Latitude': lat, 'Longitude': lon})
            except:
                continue
    return stations

# ==================
# 3️⃣ Draw Metro Map
# ==================
def visualize_metro_map(stations):
    G = nx.Graph()

    # Add nodes
    for s in stations:
        G.add_node(s['Station'], pos=(s['Longitude'], s['Latitude']))

    # Connect all pairs (fully connected for visualization)
    for i in range(len(stations)):
        for j in range(i + 1, len(stations)):
            dist = haversine(stations[i]['Latitude'], stations[i]['Longitude'],
                             stations[j]['Latitude'], stations[j]['Longitude'])
            G.add_edge(stations[i]['Station'], stations[j]['Station'], weight=round(dist, 2))

    # Draw network map
    pos = nx.get_node_attributes(G, 'pos')
    plt.figure(figsize=(12, 10))
    nx.draw_networkx_nodes(G, pos, node_color='lightblue', node_size=400, edgecolors='black')
    nx.draw_networkx_edges(G, pos, edge_color='gray', alpha=0.5, width=0.8)
    nx.draw_networkx_labels(G, pos, font_size=7, font_weight='bold')

    plt.title("Delhi Metro Network Map (Without Edge Labels)", fontsize=12)
    plt.xlabel("Longitude")
    plt.ylabel("Latitude")
    plt.tight_layout()
    plt.show()

    # Print edge costs separately
    print("\n===================================")
    print(" Delhi Metro Edge Distances (in km)")
    print("===================================\n")
    for (u, v, w) in G.edges(data='weight'):
        print(f"{u} ↔ {v} : {w} km")

# =========
# 4️⃣ Main
# =========
def main():
    filename = "DelhiMetro.csv"
    stations = load_stations(filename)
    visualize_metro_map(stations)

if __name__ == "__main__":
    main()